### ISSUE TITLE
上传的时候出现socket.error;[Errno 60]Operation timed out

### ISSUE THREAD

**Issue by psyvirgin** [skywind3000/markpress#1]
psydeMac-Pro:wordpress psy$ python /Users/psy/workspace/markpress/markpress.py post.1.md
['/Users/psy/workspace/markpress/markpress.py', 'post.1.md']
[synchronizing: post.1.md]
writing: /Users/psy/workspace/wordpress/data/post.1.html
blogpost: creating published post '用markpress写博客'...
Traceback (most recent call last):
  File "/Users/psy/workspace/markpress/markpress.py", line 10, in <module>
    wordpress.main()
  File "/Users/psy/workspace/markpress/lib/wordpress.py", line 338, in main
    wp.synchronize(filename, OPTIONS.force, True)
  File "/Users/psy/workspace/markpress/lib/wordpress.py", line 310, in synchronize
    self.config.wordpress(opt)
  File "/Users/psy/workspace/markpress/lib/wordpress.py", line 248, in wordpress
    blog.create()
  File "/Users/psy/workspace/markpress/lib/blogpost.py", line 554, in create
    self.post()
  File "/Users/psy/workspace/markpress/lib/blogpost.py", line 617, in post
    self.id = self.server.newPost(post, self.is_published())
  File "/Users/psy/workspace/markpress/lib/wordpresslib.py", line 265, in newPost
    idNewPost = int(self._server.metaWeblog.newPost(self.blogId, self.user, self.password, blogContent, 0))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1308, in single_request
    self.send_content(h, request_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1456, in send_content
    connection.endheaders(request_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 60] Operation timed out

**Comment by skywind3000** [comment]
我现在使用 https://github.com/skywind3000/vimpress 发 wordpress，本项目已经废弃了。

**Comment by psyvirgin** [comment]
好的   谢谢  我来看看
