### ISSUE TITLE
The wordpress_xmlrpc module is not found despite being installed

### ISSUE THREAD

**Issue by asitemade4u** [skywind3000/markpress#3]
Hi,
I am trying the script on an Ubuntu desktop.
The installation went well but I get this error when trying to execute

`markpress -n mypost.md` 

from the Terminal:

```
Traceback (most recent call last):
  File "/home/stsinc/.local/app/markpress/bin/markpress.py", line 12, in <module>
    nextpress.main()
  File "/home/stsinc/.local/app/markpress/lib/nextpress.py", line 226, in main
    wp = config.wp_client()
  File "/home/stsinc/.local/app/markpress/lib/config.py", line 146, in wp_client
    import wordpress2
  File "/home/stsinc/.local/app/markpress/lib/wordpress2.py", line 13, in <module>
    import wordpress_xmlrpc
ModuleNotFoundError: No module named 'wordpress_xmlrpc'
```
I checked if the `wordpress_xmlrpc` was installed on my computer by doing: `pip install python-wordpress-xmlrpc` and it is already at the last version.

What am I doing wrong?
S.

**Comment by skywind3000** [comment]
How many python interpreters do you have in your system ?? Will `pip` and `python` will run in the same environment ??

**Comment by asitemade4u** [comment]
I know I have at least two versions of Python running, 2.7 and 3.x
I also have two pip installed as a result, one for each version of Python.

⁣S.
